//! MQTT v5.0 Properties
//! ([§2.2.2 — Properties](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901027)).
//!
//! Properties are a variable-length, optional section of the variable
//! header introduced in v5.0. Each property is identified by a
//! one-byte identifier and carries a typed value. Conformance:
//! `[MQTT-2.2.2-1]`, `[MQTT-2.2.2-2]`.
use super::*;

/// One MQTT v5.0 property
/// ([§2.2.2.2 — Property](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901029)).
///
/// Each variant tags the property identifier and carries the payload
/// in the spec-mandated representation. Receiving an unknown
/// identifier is a Malformed Packet.
///
/// The companion [`PropertyType`] enum (generated by `strum`'s
/// `EnumDiscriminants`) enumerates the identifiers without their
/// payloads and is used to report which property triggered a
/// [`PropertiesError`].
#[derive(Debug, PartialEq, Eq, Clone, EnumDiscriminants)]
#[strum_discriminants(derive(Hash, EnumIter, Display))]
#[strum_discriminants(name(PropertyType))]
pub enum Property {
    /// `0x01` Payload Format Indicator
    /// ([§3.3.2.3.2](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901111)).
    /// Conformance: `[MQTT-3.3.2-5]`.
    PayloadFormatIndicator(FormatIndicator),
    /// `0x02` Message Expiry Interval in seconds
    /// ([§3.3.2.3.3](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901112)).
    MessageExpiryInterval(u32),
    /// `0x03` Content Type
    /// ([§3.3.2.3.9](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901118)).
    ContentType(Utf8String),
    /// `0x08` Response Topic
    /// ([§3.3.2.3.5](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901114)).
    ResponseTopic(Topic),
    /// `0x09` Correlation Data
    /// ([§3.3.2.3.6](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901115)).
    CorrelationData(BinaryData),
    /// `0x0B` Subscription Identifier
    /// ([§3.8.2.1.2](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901166)).
    ///
    /// A value of `0` is a Protocol Error
    /// ([MQTT-3.8.2-2]), hence the [`NonZero`] payload.
    SubscriptionIdentifier(NonZero<u64>),
    /// `0x11` Session Expiry Interval in seconds
    /// ([§3.1.2.11.2](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901048)).
    SessionExpiryInterval(u32),
    /// `0x12` Assigned Client Identifier
    /// ([§3.2.2.3.7](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901087)).
    AssignedClientIdentifier(Utf8String),
    /// `0x13` Server Keep Alive in seconds
    /// ([§3.2.2.3.14](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901094)).
    ServerKeepAlive(u16),
    /// `0x15` Authentication Method
    /// ([§3.1.2.11.9](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901055)).
    /// Conformance: `[MQTT-3.1.2-20]`, `[MQTT-3.1.2-21]`.
    AuthenticationMethod(Utf8String),
    /// `0x16` Authentication Data
    /// ([§3.1.2.11.10](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901056)).
    /// Conformance: `[MQTT-3.1.2-22]`.
    AuthenticationData(BinaryData),
    /// `0x17` Request Problem Information
    /// ([§3.1.2.11.7](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901053)).
    RequestProblemInformation(bool),
    /// `0x18` Will Delay Interval in seconds
    /// ([§3.1.3.2.2](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901062)).
    WillDelayInterval(u32),
    /// `0x19` Request Response Information
    /// ([§3.1.2.11.6](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901052)).
    RequestResponseInformation(bool),
    /// `0x1A` Response Information
    /// ([§3.2.2.3.15](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901095)).
    ResponseInformation(Utf8String),
    /// `0x1C` Server Reference
    /// ([§3.2.2.3.16](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901096)).
    ServerReference(Utf8String),
    /// `0x1F` Reason String
    /// ([§3.2.2.3.9](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901089)).
    ReasonString(Utf8String),
    /// `0x21` Receive Maximum
    /// ([§3.1.2.11.3](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901049)).
    ///
    /// It is a Protocol Error to include this property more than once
    /// or for it to have the value 0 ([MQTT-3.1.2-23]), hence the
    /// [`NonZero`] payload.
    ReceiveMaximum(NonZero<u16>),
    /// `0x22` Topic Alias Maximum
    /// ([§3.1.2.11.5](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901051)).
    TopicAliasMaximum(u16),
    /// `0x23` Topic Alias
    /// ([§3.3.2.3.4](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901113)).
    /// A value of 0 is a Protocol Error ([MQTT-3.3.2-8]).
    TopicAlias(NonZero<u16>),
    /// `0x24` Maximum QoS
    /// ([§3.2.2.3.4](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901084)).
    /// Conformance: `[MQTT-3.2.2-12]`.
    MaximumQoS(MaximumQoS),
    /// `0x25` Retain Available
    /// ([§3.2.2.3.5](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901085)).
    RetainAvailable(bool),
    /// `0x26` User Property name/value pair
    /// ([§3.1.2.11.8](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901054)).
    ///
    /// May appear multiple times; order is significant ([MQTT-3.1.2-19]).
    UserProperty(Utf8String, Utf8String),
    /// `0x27` Maximum Packet Size
    /// ([§3.1.2.11.4](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901050)).
    /// A value of 0 is a Protocol Error ([MQTT-3.1.2-25]).
    MaximumPacketSize(NonZero<u32>),
    /// `0x28` Wildcard Subscription Available
    /// ([§3.2.2.3.11](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901091)).
    WildcardSubscriptionAvailable(bool),
    /// `0x29` Subscription Identifiers Available
    /// ([§3.2.2.3.12](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901092)).
    SubscriptionIdentifiersAvailable(bool),
    /// `0x2A` Shared Subscription Available
    /// ([§3.2.2.3.13](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901093)).
    SharedSubscriptionAvailable(bool),
}

/// Paired Authentication Method / Authentication Data used by MQTT v5
/// enhanced authentication
/// ([§4.12](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901256)).
///
/// Makes invalid states unrepresentable: the spec requires that
/// Authentication Data is only sent when an Authentication Method is
/// present ([MQTT-3.1.2-21]).
#[derive(Debug, PartialEq, Eq, Clone)]
pub enum AuthenticationKind {
    /// Only an Authentication Method is set; no Authentication Data.
    WithoutData {
        /// Authentication Method name.
        method: Utf8String,
    },
    /// Both an Authentication Method and its opaque Authentication
    /// Data are set.
    WithData {
        /// Authentication Method name.
        method: Utf8String,
        /// Authentication Data payload.
        data: BinaryData,
    },
}

impl AuthenticationKind {
    /// Builds an [`AuthenticationKind`] from parsed properties.
    ///
    /// Returns [`MissingAuthenticationMethodError`] if Authentication
    /// Data is present without Authentication Method, which is a
    /// Protocol Error ([MQTT-3.1.2-21]).
    pub fn try_from_parts(
        (method, data): (Option<Utf8String>, Option<BinaryData>),
    ) -> Result<Option<Self>, MissingAuthenticationMethodError> {
        match (method, data) {
            (None, None) => Ok(None),
            (Some(method), None) => Ok(Some(AuthenticationKind::WithoutData { method })),
            (Some(method), Some(data)) => Ok(Some(AuthenticationKind::WithData { method, data })),
            (None, Some(_)) => Err(MissingAuthenticationMethodError),
        }
    }
}

/// Error returned when decoding a property identifier that is outside
/// the set defined by [§2.2.2.2](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901029).
///
/// An unknown identifier is a Malformed Packet
/// ([MQTT-1.5.5-1], [MQTT-2.2.2-1]).
#[derive(Debug, PartialEq, Eq, Clone, Copy, Error)]
#[error("Invalid property type: {value}")]
#[repr(transparent)]
pub struct InvalidPropertyTypeError {
    /// Offending Variable Byte Integer property identifier.
    pub value: u64,
}

/// Error returned when a property that is only allowed once appears
/// more than once in the same property section
/// ([§2.2.2.1](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901028)).
///
/// This is a Protocol Error; conformance: `[MQTT-2.2.2-2]`.
#[derive(Debug, PartialEq, Eq, Clone, Copy, Error)]
#[error("Property {property_type} is required to appear at most once, but is duplicated")]
#[repr(transparent)]
pub struct DuplicatedPropertyError {
    /// The property type that was duplicated.
    pub property_type: PropertyType,
}

/// Error returned when a property appears in a packet that is not
/// permitted to carry it
/// ([§2.2.2](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901027)).
///
/// Each control packet type has a fixed set of admissible properties;
/// mixing them is a Protocol Error.
#[derive(Debug, PartialEq, Eq, Clone, Copy, Error)]
#[error("The packet cannot contain a property of type {property_type}")]
#[repr(transparent)]
pub struct UnsupportedPropertyError {
    /// The property type that is not allowed by the containing packet.
    pub property_type: PropertyType,
}

/// Error returned when the parsed User Property count exceeds the
/// `ParserSettings::max_user_properties_len` limit.
///
/// Used to guard against resource-exhaustion on the parse side.
#[derive(Debug, PartialEq, Eq, Clone, Copy, Error)]
#[error("The number of user properties exceeds the maximum allowed")]
#[repr(transparent)]
pub struct TooManyUserPropertiesError;

/// Error returned when the parsed Subscription Identifier count
/// exceeds the
/// `ParserSettings::max_subscription_identifiers_len` limit.
#[derive(Debug, PartialEq, Eq, Clone, Copy, Error)]
#[error("The number of subscription identifiers exceeds the maximum allowed")]
#[repr(transparent)]
pub struct TooManySubscriptionIdentifiersError;

/// Error returned when Authentication Data is present without the
/// paired Authentication Method.
///
/// Required by [MQTT-3.1.2-21]; see [`AuthenticationKind`].
#[derive(Debug, PartialEq, Eq, Clone, Copy, Error)]
#[error(
    "Properties included {}, but {} is required",
    PropertyType::AuthenticationData,
    PropertyType::AuthenticationMethod
)]
#[repr(transparent)]
pub struct MissingAuthenticationMethodError;

/// Errors raised while aggregating an individual [`Property`] stream
/// into a packet-specific `*Properties` struct
/// ([§2.2.2](https://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html#_Toc3901027)).
#[derive(Debug, PartialEq, Eq, Clone, Copy, Error)]
pub enum PropertiesError {
    /// A property that MUST appear at most once was repeated.
    #[error(transparent)]
    DuplicatedProperty(#[from] DuplicatedPropertyError),
    /// Parser limit on User Properties was exceeded.
    #[error(transparent)]
    TooManyUserProperties(#[from] TooManyUserPropertiesError),
    /// Parser limit on Subscription Identifiers was exceeded.
    #[error(transparent)]
    TooManySubscriptionIdentifiers(#[from] TooManySubscriptionIdentifiersError),
    /// Authentication Data was sent without Authentication Method.
    #[error(transparent)]
    MissingAuthenticationMethod(#[from] MissingAuthenticationMethodError),
    /// A property appeared in a packet that does not permit it.
    #[error(transparent)]
    UnsupportedProperty(#[from] UnsupportedPropertyError),
}

impl TryFrom<u64> for PropertyType {
    type Error = InvalidPropertyTypeError;

    #[inline]
    fn try_from(value: u64) -> Result<Self, Self::Error> {
        match value {
            0x01 => Ok(PropertyType::PayloadFormatIndicator),
            0x02 => Ok(PropertyType::MessageExpiryInterval),
            0x03 => Ok(PropertyType::ContentType),
            0x08 => Ok(PropertyType::ResponseTopic),
            0x09 => Ok(PropertyType::CorrelationData),
            0x0B => Ok(PropertyType::SubscriptionIdentifier),
            0x11 => Ok(PropertyType::SessionExpiryInterval),
            0x12 => Ok(PropertyType::AssignedClientIdentifier),
            0x13 => Ok(PropertyType::ServerKeepAlive),
            0x15 => Ok(PropertyType::AuthenticationMethod),
            0x16 => Ok(PropertyType::AuthenticationData),
            0x17 => Ok(PropertyType::RequestProblemInformation),
            0x18 => Ok(PropertyType::WillDelayInterval),
            0x19 => Ok(PropertyType::RequestResponseInformation),
            0x1A => Ok(PropertyType::ResponseInformation),
            0x1C => Ok(PropertyType::ServerReference),
            0x1F => Ok(PropertyType::ReasonString),
            0x21 => Ok(PropertyType::ReceiveMaximum),
            0x22 => Ok(PropertyType::TopicAliasMaximum),
            0x23 => Ok(PropertyType::TopicAlias),
            0x24 => Ok(PropertyType::MaximumQoS),
            0x25 => Ok(PropertyType::RetainAvailable),
            0x26 => Ok(PropertyType::UserProperty),
            0x27 => Ok(PropertyType::MaximumPacketSize),
            0x28 => Ok(PropertyType::WildcardSubscriptionAvailable),
            0x29 => Ok(PropertyType::SubscriptionIdentifiersAvailable),
            0x2A => Ok(PropertyType::SharedSubscriptionAvailable),
            value => Err(InvalidPropertyTypeError { value }),
        }
    }
}

impl From<PropertyType> for u64 {
    fn from(value: PropertyType) -> Self {
        match value {
            PropertyType::PayloadFormatIndicator => 0x01,
            PropertyType::MessageExpiryInterval => 0x02,
            PropertyType::ContentType => 0x03,
            PropertyType::ResponseTopic => 0x08,
            PropertyType::CorrelationData => 0x09,
            PropertyType::SubscriptionIdentifier => 0x0B,
            PropertyType::SessionExpiryInterval => 0x11,
            PropertyType::AssignedClientIdentifier => 0x12,
            PropertyType::ServerKeepAlive => 0x13,
            PropertyType::AuthenticationMethod => 0x15,
            PropertyType::AuthenticationData => 0x16,
            PropertyType::RequestProblemInformation => 0x17,
            PropertyType::WillDelayInterval => 0x18,
            PropertyType::RequestResponseInformation => 0x19,
            PropertyType::ResponseInformation => 0x1A,
            PropertyType::ServerReference => 0x1C,
            PropertyType::ReasonString => 0x1F,
            PropertyType::ReceiveMaximum => 0x21,
            PropertyType::TopicAliasMaximum => 0x22,
            PropertyType::TopicAlias => 0x23,
            PropertyType::MaximumQoS => 0x24,
            PropertyType::RetainAvailable => 0x25,
            PropertyType::UserProperty => 0x26,
            PropertyType::MaximumPacketSize => 0x27,
            PropertyType::WildcardSubscriptionAvailable => 0x28,
            PropertyType::SubscriptionIdentifiersAvailable => 0x29,
            PropertyType::SharedSubscriptionAvailable => 0x2A,
        }
    }
}

#[cfg(test)]
mod marker_trait_guards {
    use super::*;

    trait MustNotImplementHash {}
    impl<T: core::hash::Hash> MustNotImplementHash for T {}

    trait MustNotImplementOrd {}
    impl<T: Ord> MustNotImplementOrd for T {}

    trait MustNotImplementPartialOrd {}
    impl<T: PartialOrd> MustNotImplementPartialOrd for T {}

    impl MustNotImplementHash for TooManyUserPropertiesError {}
    impl MustNotImplementOrd for TooManyUserPropertiesError {}
    impl MustNotImplementPartialOrd for TooManyUserPropertiesError {}

    impl MustNotImplementHash for MissingAuthenticationMethodError {}
    impl MustNotImplementOrd for MissingAuthenticationMethodError {}
    impl MustNotImplementPartialOrd for MissingAuthenticationMethodError {}

    impl MustNotImplementHash for TooManySubscriptionIdentifiersError {}
    impl MustNotImplementOrd for TooManySubscriptionIdentifiersError {}
    impl MustNotImplementPartialOrd for TooManySubscriptionIdentifiersError {}

    fn assert_not_hash<T: MustNotImplementHash>() {}
    fn assert_not_ord<T: MustNotImplementOrd>() {}
    fn assert_not_partial_ord<T: MustNotImplementPartialOrd>() {}

    #[test]
    fn marker_errors_are_not_ordered_or_hashed() {
        assert_not_hash::<TooManyUserPropertiesError>();
        assert_not_ord::<TooManyUserPropertiesError>();
        assert_not_partial_ord::<TooManyUserPropertiesError>();

        assert_not_hash::<MissingAuthenticationMethodError>();
        assert_not_ord::<MissingAuthenticationMethodError>();
        assert_not_partial_ord::<MissingAuthenticationMethodError>();

        assert_not_hash::<TooManySubscriptionIdentifiersError>();
        assert_not_ord::<TooManySubscriptionIdentifiersError>();
        assert_not_partial_ord::<TooManySubscriptionIdentifiersError>();
    }
}
