[package]
name = "sansio-mqtt-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
bon = { workspace = true }
bytes = { workspace = true }
bytestring = { workspace = true }
sansio = { workspace = true }
semver = { workspace = true }
thiserror = { workspace = true }
